# Generated by Django 3.2.25 on 2025-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa',
            field=models.BooleanField(default=False),
        ),
    ]
